sudo: required

language: java

services:
  - docker

branches:
  only:
    - master
    - stable

install: true

script:
  - ./gradlew clean classes
  - ./gradlew library:test library:wmsTest web-service:test

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew library:bintrayUpload
    on:
      branch: master
