sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker

branches:
  only:
    - master
    - stable

install: true

script:
  - ./gradlew clean classes library:test library:wmsTest web-service:test web-service:bootJar web-service:buildDockerImage

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew library:bintrayUpload
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./gradlew web-service:pushDockerImages
    on:
      branch: master
